Repository CloakingGhost/book-review, pull requests merged in 2025-03, with the labels that each got.

#67 [BK-64] [refactor] 이미지 생성 시 유저 정보 추가
  backend/src/main/java/org/example/book_report/controller/ImageController.java
  backend/src/main/java/org/example/book_report/dto/response/UserCardImageResponseDto.java
  backend/src/main/java/org/example/book_report/service/ImageService.java
Labels: refactor

#69 [BK-65] [feat] FE-유저가 생성한 카드 이미지 렌더링
  frontend/src/App.jsx
  frontend/src/assets/base1.png
  frontend/src/assets/base2.png
  frontend/src/assets/base3.png
  frontend/src/assets/base4.png
  frontend/src/assets/base5.png
  frontend/src/assets/base6.png
  frontend/src/assets/base7.png
  frontend/src/assets/base8.png
  frontend/src/assets/base9.png
  frontend/src/components/card/BaseCardImageLists.jsx
  frontend/src/components/card/CardCreateSection.jsx
  frontend/src/components/card/CardPreview.jsx
  frontend/src/components/card/UserCardImageLists.jsx
  frontend/src/pages/BookReview.jsx
  frontend/src/store/slices/selectedCardSlice.js
  frontend/src/store/store.js
  frontend/src/styles/Card.module.css
Labels: feat

#70 [BK-69] [fix] 이미지 에러 해결
  backend/src/main/java/org/example/book_report/repository/ImageRepository.java
  backend/src/main/java/org/example/book_report/repository/UserImageRepository.java
  backend/src/main/java/org/example/book_report/service/BookReviewService.java
  frontend/src/pages/BookReview.jsx
Labels: fix

#72 [BK-82] [fix] slice import 오류 해결
  frontend/src/store/store.js
Labels: fix

#74 [BK-83] [style] 카드-이미지-스타일-변경
  frontend/src/components/card/CardPreview.jsx
  frontend/src/components/card/UserCardImageLists.jsx
  frontend/src/styles/Card.module.css
Labels: style

#76 [BK-86] [feat] 이미지 생성 로직 및 기타 세부 로직 수정
  frontend/src/api/imageApi.js
  frontend/src/assets/base1.png
  frontend/src/assets/base2.png
  frontend/src/assets/base4.png
  frontend/src/assets/base5.png
  frontend/src/assets/base6.png
  frontend/src/assets/base7.png
  frontend/src/assets/base8.png
  frontend/src/assets/base9.png
  frontend/src/components/card/BaseCardImageLists.jsx
  frontend/src/components/card/CardCreateSection.jsx
  frontend/src/components/card/CardPreview.jsx
  frontend/src/components/card/UserCardImageLists.jsx
  frontend/src/styles/Card.module.css
Labels: refactor

#84 [BK-87] [feat] FE 감상문 상세 페이지 구성 및 api 요청
  backend/src/main/java/org/example/book_report/dto/response/BookReviewDetailResponseDto.java
  backend/src/main/java/org/example/book_report/repository/ImageRepository.java
  backend/src/main/java/org/example/book_report/repository/UserImageRepository.java
  backend/src/main/java/org/example/book_report/service/BookReviewService.java
  frontend/src/components/card/CardPreview.jsx
  frontend/src/pages/BookReivewDetatil.jsx
  frontend/src/pages/BookReviewDetail.jsx
  frontend/src/router/index.jsx
  frontend/src/styles/BookReviewDetail.module.css
Labels: feat

#86 [BK-93] [refactor] 한줄평 입력값 오류 해결
  frontend/src/components/card/CardPreview.jsx
Labels: refactor

#88 [BK-95] [feat] BE-유저별 감상문 모음 조회
  backend/src/main/java/org/example/book_report/controller/BookReviewController.java
  backend/src/main/java/org/example/book_report/dto/response/UserBookReviewsResponseDto.java
  backend/src/main/java/org/example/book_report/repository/BookReviewRepository.java
  backend/src/main/java/org/example/book_report/service/BookReviewService.java
Labels: feat

#90 [BK-92] [feat] 감상문 상세 페이지 삭제, 공개여부 변환 및 세부 로직 구현
  frontend/src/pages/BookReviewDetail.jsx
  frontend/src/styles/BookReviewDetail.module.css
Labels: feat

#91 [BK-100] [fix] import 오류 해결 후 다시 pr
  frontend/src/pages/BookReviewDetail.jsx
Labels: fix

#94 [BK-104] [refactor] 감상문 삭제 및 도서 검색 수정
  backend/src/main/java/org/example/book_report/controller/BookReviewController.java
  backend/src/main/java/org/example/book_report/repository/BookRepository.java
Labels: refactor

#95 [BK-101] [refactor] 기본 이미지 오류 해결
  frontend/src/components/card/BaseCardImageLists.jsx
Labels: refactor

#97 [BK-80] [chore] base3.png 수정
  frontend/src/assets/base3.png
Labels: chore

#98 [BK-103] [feat] 감상문 작성 페이지 오류 해결
  frontend/src/api/bookApi.js
  frontend/src/pages/BookReview.jsx
Labels: feat

#101 [BK-105] [feat] 감상문 작성 페이지 접근 제한
  frontend/src/components/ProtectedRouter.jsx
  frontend/src/router/index.jsx
Labels: feat

#103 Feature/bk 107 fe infinite scroll for main page
  backend/src/main/java/org/example/book_report/controller/BookReviewController.java
  backend/src/main/java/org/example/book_report/service/BookReviewService.java
  backend/src/main/resources/application.properties
  frontend/src/api/reviewApi.js
  frontend/src/pages/Home.jsx
  frontend/src/styles/BookReviewCard.module.css
  frontend/src/styles/Home.module.css
Labels: feat

#105 [BK-111] [style] 로고 추가 및 헤더 디자인 변경
  frontend/index.html
  frontend/public/book.png
  frontend/src/components/Header.jsx
  frontend/src/styles/Header.module.css
Labels: style

#106 Feature/bk 107 fe infinite scroll for main page
  backend/src/main/java/org/example/book_report/controller/BookReviewController.java
  backend/src/main/resources/application.properties
  frontend/src/api/reviewApi.js
  frontend/src/pages/Home.jsx
Labels: feat

#108 [BK-105] [fix] 감상문 작성 페이지 세부처리
  frontend/src/pages/BookReview.jsx
  frontend/src/store/slices/selectedCardSlice.js
Labels: fix

#112 [BK-112] [style] 웹 페이지 디자인
  frontend/index.html
  frontend/src/assets/loading.png
  frontend/src/assets/lock.png
  frontend/src/components/Header.jsx
  frontend/src/components/card/CardPreview.jsx
  frontend/src/components/card/UserCardImageLists.jsx
  frontend/src/pages/BookReviewDetail.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/NotFound.jsx
  frontend/src/pages/Signup.jsx
  frontend/src/styles/BookReviewDetail.module.css
  frontend/src/styles/Card.module.css
  frontend/src/styles/Header.module.css
  frontend/src/styles/NotFound.module.css
  frontend/src/styles/Signup.module.css
  frontend/src/styles/common.css
Labels: style

#113 Feature/bk 105 fe 감상문 작성 페이지 세부처리
  frontend/src/pages/BookReview.jsx
Labels: fix

#114 [BK-115] [refactor] 기타 오류 해결
  backend/src/main/java/org/example/book_report/dto/response/BookReviewDetailResponseDto.java
  frontend/src/pages/BookReviewDetail.jsx
  frontend/src/pages/UserBookReview.jsx
  frontend/src/styles/BookReviewCard.module.css
  frontend/src/styles/BookReviewDetail.module.css
  frontend/src/styles/CardComponents.module.css
  frontend/src/styles/Home.module.css
Labels: refactor

#119 [BK-128] [docs] 유저 플로우
  README.md
  document/readme-file/erd.png
  document/readme-file/user-flow.png
  document/readme-file/wire-frame.png
Labels: documentation

#120 [BK-127] [docs] 와이어 프레임
  README.md
Labels: documentation

#122 [BK-129] [docs] 기술 스택
  README.md
  document/readme-file/tech-skill.md
Labels: documentation

#123 [BK-126] [docs] README.md 수정
  README.md
  document/readme-file/architecture.png
  scrap/README.md
  scrap/book-scrap/api.py
  scrap/book-scrap/db.py
  scrap/book-scrap/main.py
Labels: documentation

#124 Docs/bk 126 조원 별 깃허브 링크
  scrap/README.md
Labels: documentation

#125 [BK-131] [docs] update README.md
  README.md
  document/readme-file/deploy.md
Labels: documentation

#126 [BK-132] [docs] update README.md
  backend/src/main/java/org/example/book_report/entity/User.java
  document/readme-file/erd-drawio.png
Labels: documentation

#129 [BK-133] [docs] update README.md
  README.md
Labels: documentation

#130 [BK-134] [chore] EC2 교체
  README.md
Labels: documentation

#133 Docs/bk 136 db 문서 수정
  README.md
  docker-compose.yml
  scrap/README.md
Labels: documentation
