Repository CloakingGhost/book-review, pull requests merged in 2025-02, with the labels that each got.

#1 [BK-3] [chore] husky 설정
  .gitignore
  .gitmessage
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: config

#3 [BK-4] [chore] react 프로젝트 빌드
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/vite.config.js
Labels: config

#8 Feature/bk 19 be security config
  backend/compose.yaml
  backend/src/main/java/org/example/book_report/common/BaseTimeEntity.java
  backend/src/main/java/org/example/book_report/config/JpaConfig.java
  backend/src/main/java/org/example/book_report/config/SecurityConfig.java
  backend/src/main/java/org/example/book_report/controller/AuthController.java
  backend/src/main/java/org/example/book_report/dto/requestDto/SignupRequestDto.java
  backend/src/main/java/org/example/book_report/dto/responseDto/SignupResponseDto.java
  backend/src/main/java/org/example/book_report/entity/Role.java
  backend/src/main/java/org/example/book_report/entity/User.java
  backend/src/main/java/org/example/book_report/repository/AuthRepository.java
  backend/src/main/java/org/example/book_report/service/AuthService.java
Labels: config

#10 [BK-8] [feat] frontend 초기 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/layouts/RootLayout.jsx
  frontend/src/pages/BookReivewDetatil.jsx
  frontend/src/pages/BookReviewCreate.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/NotFound.jsx
  frontend/src/pages/Signup.jsx
  frontend/src/pages/UserBookReview.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/authSlice.js
  frontend/src/store/store.js
Labels: config

#20 [BK-21] [feat] 회원가입 폼 생성
  frontend/src/pages/Signup.jsx
Labels: feat

#21 [BK-22] [feat] 회원가입 시 아이디 중복확인 Api 요청
  frontend/src/pages/Signup.jsx
Labels: feat

#28 [BK-23] [feat] 회원가입 Api 요청 & 아이디 중복 확인 및 비밀번호 일치여부 확인 기능 구현
  frontend/src/pages/Signup.jsx
Labels: feat

#30 [BK-37] [refactor] router 경로 재설정 및 감상문 작성페이지 파일 이름 변경
  frontend/src/pages/BookReview.jsx
  frontend/src/pages/BookReviewCreate.jsx
  frontend/src/router/index.jsx
Labels: feat

#31 [BK-38] [refactor] react router 감상문 작성, 수정 경로 분리
  frontend/src/router/index.jsx
Labels: feat

#33 [BK-41] [chore] vite 개발용 프록시 및 gzip 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/authApi.js
  frontend/src/api/axios.js
  frontend/src/api/bookApi.js
  frontend/src/api/imageApi.js
  frontend/src/api/reviewApi.js
  frontend/vite.config.js
Labels: config

#34 [BK-48] [refactor] 아이디 중복확인 api 요청 수정
  frontend/src/pages/Signup.jsx
Labels: refactor

#38 [BK-40] [refactor] 회원가입 예외처리 추가 및 수정
  frontend/src/pages/Signup.jsx
Labels: refactor

#45 [BK-55] [feat] BE-책-표지-및-카드-이미지
  backend/build.gradle
  backend/src/main/java/org/example/book_report/config/AwsS3Config.java
  backend/src/main/java/org/example/book_report/controller/ImageController.java
  backend/src/main/java/org/example/book_report/dto/request/ImageUploadRequestDto.java
  backend/src/main/java/org/example/book_report/dto/response/ImageResponseDto.java
  backend/src/main/java/org/example/book_report/dto/response/ImageUploadResponseDto.java
  backend/src/main/java/org/example/book_report/entity/Image.java
  backend/src/main/java/org/example/book_report/entity/ImageType.java
  backend/src/main/java/org/example/book_report/entity/User.java
  backend/src/main/java/org/example/book_report/entity/UserImage.java
  backend/src/main/java/org/example/book_report/repository/ImageRepository.java
  backend/src/main/java/org/example/book_report/repository/UserImageRepository.java
  backend/src/main/java/org/example/book_report/service/ImageService.java
  backend/src/main/java/org/example/book_report/service/S3Service.java
Labels: feat

#50 [BK-57] [refactor] 이미지 생성 및 삭제 로직 수정
  backend/src/main/java/org/example/book_report/dto/request/ImageUploadRequestDto.java
  backend/src/main/java/org/example/book_report/dto/response/ImageUploadResponseDto.java
  backend/src/main/java/org/example/book_report/entity/Image.java
  backend/src/main/java/org/example/book_report/repository/UserImageRepository.java
  backend/src/main/java/org/example/book_report/service/ImageService.java
Labels: refactor

#52 [BK-66] [feat] 사용자 업로드 카드 이미지 조회 기능 구현
  backend/src/main/java/org/example/book_report/controller/BookReviewController.java
  backend/src/main/java/org/example/book_report/dto/response/UserCardImageResponseDto.java
  backend/src/main/java/org/example/book_report/repository/ImageRepository.java
  backend/src/main/java/org/example/book_report/repository/UserImageRepository.java
  backend/src/main/java/org/example/book_report/service/BookReviewService.java
  frontend/src/api/axios.js
  frontend/src/api/imageApi.js
Labels: feat

#53 [BK-33] [feat] 도서 검색 모달창 및 트리거, 감상문 작성 기능
  frontend/src/pages/BookReview.jsx
Labels: feat
